### ISSUE TITLE
Checklist Geral do Trabalho

### ISSUE THREAD

**Issue by pedrobarbosaocb** [pedrobarbosaocb/Compiladores-2024-1_fga_unb#1]
- [ ] Levantamento teórico sobre os assuntos abordados no trabalho
    - [ ] numeração de figuras
    - [ ] tabelas
    - [ ] formulas.

- [ ] O trabalho deve conter outras derivações mais à esquerda, tais como
`a*b+c`, `a/b*c`

- [x] Implementação de um programa computacional em C ou C++, dos algoritmos:
    - [x] Árvore de análise
    - [x] Analisador LL(1)

- [ ] Todas as variáveis do programa devem ser descritas antes de usadas.

- [ ] Ao final o programa de mostrar a efetividade do algoritmo
apresentado, deixando ao usuário a opção pela continuação ou não da
execução do programa.
